param(
  [switch]$KeepOutput
)

$ErrorActionPreference = "Stop"

function Assert-True {
  param([bool]$Condition, [string]$Message)
  if (-not $Condition) {
    throw "ASSERTION FAILED: $Message"
  }
}

function Read-Json {
  param([string]$Path)
  return (Get-Content -LiteralPath $Path -Raw -Encoding UTF8 | ConvertFrom-Json)
}

$repoRoot = Resolve-Path -LiteralPath (Join-Path $PSScriptRoot "..")
$skillRoot = Join-Path $repoRoot "tests\fixtures\skills"
$scanScript = Join-Path $repoRoot "skill-selection-assistant\scripts\scan-local-skills.ps1"
$inferScript = Join-Path $repoRoot "skill-selection-assistant\scripts\infer-route.ps1"
$recommendScript = Join-Path $repoRoot "skill-selection-assistant\scripts\recommend-skills.ps1"
$memoryScript = Join-Path $repoRoot "skill-selection-assistant\scripts\record-selection-memory.ps1"
$doctorScript = Join-Path $repoRoot "skill-selection-assistant\scripts\doctor.ps1"
$summarizeScript = Join-Path $repoRoot "skill-selection-assistant\scripts\summarize-index.py"
$installScript = Join-Path $repoRoot "scripts\install-skill.ps1"
$pythonInstallScript = Join-Path $repoRoot "scripts\install-skill.py"
$cleanScript = Join-Path $repoRoot "scripts\clean-local-artifacts.ps1"
$packageScript = Join-Path $repoRoot "scripts\package-release.ps1"
$rulesPath = Join-Path $repoRoot "skill-selection-assistant\rules\categories.json"
$outputRoot = Join-Path $env:TEMP ("skill-selection-smoke-" + [guid]::NewGuid().ToString("N"))
$indexDir = Join-Path $outputRoot ".skill-index"

try {
  New-Item -ItemType Directory -Force -Path $indexDir | Out-Null

  & $scanScript -SkillsRoot $skillRoot -OutputDir $indexDir | Out-Null

  $indexPath = Join-Path $indexDir "skills-index.json"
  $summaryPath = Join-Path $indexDir "route-summary.json"
  $manifestPath = Join-Path $indexDir "manifest.json"
  $parseCachePath = Join-Path $indexDir "parsed-skills-cache.ndjson"
  Assert-True (Test-Path -LiteralPath $rulesPath) "shared category rules should exist"
  Assert-True (Test-Path -LiteralPath $indexPath) "skills-index.json should be generated"
  Assert-True (Test-Path -LiteralPath $summaryPath) "route-summary.json should be generated"
  Assert-True (Test-Path -LiteralPath $manifestPath) "manifest.json should be generated"
  Assert-True (Test-Path -LiteralPath $parseCachePath) "parsed-skills-cache.ndjson should be generated"

  $index = Read-Json -Path $indexPath
  $manifest = Read-Json -Path $manifestPath
  $summary = Read-Json -Path $summaryPath
  Assert-True ([int]$index.raw_total -eq 11) "raw_total should be 11"
  Assert-True ([int]$index.total -eq 10) "total should preserve same-name variants and merge exact duplicates"
  Assert-True ([int]$index.duplicates_removed -eq 1) "duplicates_removed should be 1"
  Assert-True ($summary.index_scope -eq "installing-user-local-skills") "route summary should declare per-user index scope"
  Assert-True ($summary.skill_instance_dir -ne $summary.skills_root) "summary should distinguish the installed skill instance from the scanned skills root"
  Assert-True ($manifest.cache_file -eq "parsed-skills-cache.ndjson") "manifest should point to NDJSON parse cache"
  Assert-True ($summary.rules_schema_version -eq "1.5") "route summary should expose shared rules schema"
  Assert-True ($summary.output_schema_version -eq "1.6.0") "route summary should expose adaptive route schema"
  Assert-True ($null -eq $manifest.files[0].item) "manifest should not embed full parsed skill items"

  $duplicateVariants = @($index.skills | Where-Object { $_.canonical_name -eq "duplicate-tool" })
  Assert-True ($duplicateVariants.Count -eq 2) "duplicate-tool should have two content variants"
  Assert-True ((@($duplicateVariants | Where-Object { $_.dedupe_status -eq "variant" }).Count) -eq 2) "duplicate-tool variants should be marked variant"

  $frontendShortlist = Join-Path $indexDir "shortlists\domain-detail\frontend-web.json"
  $frontendSpecialtyShortlist = Join-Path $indexDir "shortlists\specialty\frontend-style-ui.json"
  $frontendAdaptiveShortlist = Join-Path $indexDir "shortlists\adaptive-leaf\specialty-frontend-style-ui-task-generate.json"
  $frontendRoute = Join-Path $indexDir "routes\domain-detail\frontend-web.json"
  Assert-True (Test-Path -LiteralPath $frontendShortlist) "frontend-web shortlist should exist"
  Assert-True (Test-Path -LiteralPath $frontendSpecialtyShortlist) "frontend-style-ui shortlist should exist"
  Assert-True (Test-Path -LiteralPath $frontendAdaptiveShortlist) "frontend-style-ui generate adaptive shortlist should exist"
  Assert-True (-not (Test-Path -LiteralPath $frontendRoute)) "frontend-web full route should not be generated by default"

  $staleFile = Join-Path $indexDir "routes\domain-detail\stale-route.json"
  New-Item -ItemType Directory -Force -Path (Split-Path -Parent $staleFile) | Out-Null
  Set-Content -LiteralPath $staleFile -Value "{}" -Encoding UTF8
  Assert-True (Test-Path -LiteralPath $staleFile) "stale route fixture should exist before rescan"
  & $scanScript -SkillsRoot $skillRoot -OutputDir $indexDir | Out-Null
  Assert-True (-not (Test-Path -LiteralPath $staleFile)) "stale route file should be removed by rescan"
  Assert-True (-not (Test-Path -LiteralPath $frontendRoute)) "default rescan should keep full routes absent"

  & $scanScript -SkillsRoot $skillRoot -OutputDir $indexDir -IncludeFullRoutes | Out-Null
  Assert-True (Test-Path -LiteralPath $frontendRoute) "frontend-web full route should exist when -IncludeFullRoutes is used"
  $fullRouteSummary = Read-Json -Path $summaryPath
  Assert-True ($fullRouteSummary.full_routes_generated -eq $true) "route summary should record full route generation"

  $frontendRouteInference = (& $inferScript -Query "build a beautiful frontend UI" -IndexDir $indexDir | Out-String | ConvertFrom-Json)
  Assert-True ($frontendRouteInference.route_type -eq "specialty") "frontend query should infer a specialty route"
  Assert-True ($frontendRouteInference.category -eq "frontend-style-ui") "frontend query should infer frontend-style-ui"
  Assert-True ($frontendRouteInference.shortlist_file -eq "shortlists/specialty/frontend-style-ui.json") "frontend inference should expose specialty shortlist file"

  $researchRouteInference = (& $inferScript -Query "analyze this academic paper and extract citations" -IndexDir $indexDir | Out-String | ConvertFrom-Json)
  Assert-True ($researchRouteInference.route_type -eq "specialty") "academic query should infer a specialty route"
  Assert-True ($researchRouteInference.category -eq "research-literature-review") "academic query should infer literature review specialty"
  Assert-True ($researchRouteInference.domain_detail -eq "academic-research") "academic query should preserve academic-research department"

  $recommendation = (& $recommendScript -Query "build a beautiful frontend UI" -Limit 3 -IndexDir $indexDir | Out-String | ConvertFrom-Json)
  Assert-True ($recommendation.route.route_type -eq "adaptive_leaf") "recommendation should use adaptive leaf route"
  Assert-True ($recommendation.route.category -eq "specialty=frontend-style-ui|task=generate") "recommendation should use frontend-style-ui generate route"
  Assert-True ($recommendation.selection.source_file -like "*shortlists*") "recommendation should read from shortlist"
  Assert-True ([int]$recommendation.selection.returned -gt 0) "recommendation should return candidates"
  Assert-True ($recommendation.selection.candidates[0].name -eq "frontend-design") "frontend-design should be first for frontend UI query"
  Assert-True ($recommendation.selection.merged_variants -eq $true) "recommendation should merge same-name variants by default"
  Assert-True (-not ($recommendation.selection.candidates[0].PSObject.Properties.Name -contains "variants")) "single-variant recommendations should omit variant details"

  $projectIndexDir = Join-Path $outputRoot "project-index"
  & $scanScript -SkillsRoot $skillRoot -OutputDir $projectIndexDir | Out-Null
  $projectRecommendation = (& $recommendScript -Query "organize this bot project structure and write README" -Limit 3 -IndexDir $projectIndexDir | Out-String | ConvertFrom-Json)
  Assert-True ($projectRecommendation.route.category -eq "project-structure-readme") "project-structure query should infer project-structure-readme specialty"
  Assert-True ($projectRecommendation.route.domain_detail -eq "project-maintenance") "project-structure query should preserve project-maintenance department"
  Assert-True (@("project-helper", "readme-maintainer", "repo-cleanup-helper") -contains $projectRecommendation.selection.candidates[0].name) "project workspace skills should outrank generic coding skills"

  $dynamicRecommendation = (& $recommendScript -Query "organize this bot repo project structure and write README" -MaxRecommendations 6 -ScoreWindow 100 -IndexDir $projectIndexDir | Out-String | ConvertFrom-Json)
  Assert-True ($dynamicRecommendation.selection.recommendation_policy.mode -eq "dynamic_score_window") "omitting -Limit should use dynamic score-window recommendations"
  Assert-True ([int]$dynamicRecommendation.selection.returned -gt 0) "dynamic recommendations should return relevant candidates"
  Assert-True ([int]$dynamicRecommendation.selection.returned -le 6) "dynamic recommendations should respect MaxRecommendations"

  $autoIndexDir = Join-Path $outputRoot "auto-index"
  $autoRecommendation = (& $recommendScript -Query "build a beautiful frontend UI" -Limit 3 -IndexDir $autoIndexDir -SkillsRoot $skillRoot | Out-String | ConvertFrom-Json)
  Assert-True (Test-Path -LiteralPath (Join-Path $autoIndexDir "route-summary.json")) "recommend-skills.ps1 should auto-scan when index is missing"
  Assert-True ($autoRecommendation.index.refreshed -eq $true) "first-use recommendation should report that the local index was generated"
  Assert-True ($autoRecommendation.index.refresh_reason -eq "index_missing") "first-use recommendation should expose the index refresh reason"
  Assert-True ($autoRecommendation.route.category -eq "specialty=frontend-style-ui|task=generate") "auto-scan recommendation should infer adaptive frontend route"

  $freshnessRoot = Join-Path $outputRoot "freshness-skills"
  $freshnessIndexDir = Join-Path $outputRoot "freshness-index"
  Copy-Item -LiteralPath $skillRoot -Destination $freshnessRoot -Recurse -Force
  & $scanScript -SkillsRoot $freshnessRoot -OutputDir $freshnessIndexDir | Out-Null
  $beforeRefresh = Read-Json -Path (Join-Path $freshnessIndexDir "skills-index.json")
  $newSkillDir = Join-Path $freshnessRoot "portable-kubernetes-deployer"
  New-Item -ItemType Directory -Force -Path $newSkillDir | Out-Null
  Set-Content -LiteralPath (Join-Path $newSkillDir "SKILL.md") -Encoding UTF8 -Value @(
    "---",
    "name: portable-kubernetes-deployer",
    "description: Deploy Kubernetes applications and maintain container release workflows.",
    "---",
    "",
    "# Portable Kubernetes Deployer"
  )
  $refreshedRecommendation = (& $recommendScript -Query "deploy a Kubernetes application" -Limit 3 -IndexDir $freshnessIndexDir -SkillsRoot $freshnessRoot | Out-String | ConvertFrom-Json)
  $afterRefresh = Read-Json -Path (Join-Path $freshnessIndexDir "skills-index.json")
  Assert-True ($refreshedRecommendation.index.refreshed -eq $true) "recommendation should refresh when the installing user's local skill library changes"
  Assert-True ($refreshedRecommendation.index.refresh_reason -eq "local_skill_library_changed") "stale-index refresh should expose the local-library change reason"
  Assert-True ([int]$afterRefresh.raw_total -eq ([int]$beforeRefresh.raw_total + 1)) "refresh should classify a newly installed local skill"
  $newIndexedSkill = @($afterRefresh.skills | Where-Object { $_.name -eq "portable-kubernetes-deployer" })[0]
  Assert-True ($newIndexedSkill.relative_path -eq "portable-kubernetes-deployer") "scanner should generate a root-relative skill path even when Windows supplies an 8.3 short parent path"
  Assert-True (@($refreshedRecommendation.selection.candidates | Where-Object { $_.name -eq "portable-kubernetes-deployer" }).Count -eq 1) "recommendations should include a newly installed matching skill after refresh"
  $installedSkillPaths = @(
    Get-ChildItem -LiteralPath $freshnessRoot -Filter "SKILL.md" -Recurse -Force -File |
      ForEach-Object { $_.FullName }
  )
  foreach ($candidate in @($refreshedRecommendation.selection.candidates)) {
    Assert-True (Test-Path -LiteralPath $candidate.skill_md) "every recommendation should point to an installed SKILL.md"
    Assert-True ($installedSkillPaths -contains [string]$candidate.skill_md) "recommendations should come only from the scanned installing-user skills root"
  }

  Assert-True (Test-Path -LiteralPath $memoryScript) "record-selection-memory.ps1 should exist"
  $memoryResult = (& $memoryScript -Query "build a beautiful frontend UI" -Outcome selected -SelectedSkill "frontend-design" -RouteType "domain_detail" -Category "frontend-web" -IndexDir $indexDir | Out-String | ConvertFrom-Json)
  Assert-True ($memoryResult.status -eq "recorded") "memory recorder should report recorded"
  Assert-True (Test-Path -LiteralPath $memoryResult.memory) "selection memory should exist"
  $memoryText = Get-Content -LiteralPath $memoryResult.memory -Raw -Encoding UTF8
  Assert-True ($memoryText.Contains("frontend-design")) "selection memory should include selected skill"

  $memoryRankIndexDir = Join-Path $outputRoot "memory-rank-index"
  & $scanScript -SkillsRoot $skillRoot -OutputDir $memoryRankIndexDir | Out-Null
  & $memoryScript -Query "build a beautiful frontend UI" -Outcome selected -SelectedSkill "bot-plugin-helper" -RouteType "adaptive_leaf" -Category "specialty=frontend-style-ui|task=generate" -IndexDir $memoryRankIndexDir | Out-Null
  $memoryRecommendation = (& $recommendScript -Query "build a beautiful frontend UI" -Limit 3 -IndexDir $memoryRankIndexDir | Out-String | ConvertFrom-Json)
  Assert-True ($memoryRecommendation.selection.candidates[0].name -eq "bot-plugin-helper") "selection memory should influence future ranking within the active adaptive route"
  Assert-True ($memoryRecommendation.selection.candidates[0].memory_score -gt 0) "memory-boosted candidate should expose memory_score"

  Assert-True (Test-Path -LiteralPath $doctorScript) "doctor.ps1 should exist"
  Assert-True (Test-Path -LiteralPath $summarizeScript) "summarize-index.py should exist"
  $doctorIndexDir = Join-Path $outputRoot "doctor-index"
  $doctorResult = (& $doctorScript -SkillsRoot $skillRoot -IndexDir $doctorIndexDir -Fix | Out-String | ConvertFrom-Json)
  Assert-True ($doctorResult.status -eq "ok") "doctor.ps1 -Fix should report ok"
  Assert-True (Test-Path -LiteralPath (Join-Path $doctorIndexDir "route-summary.json")) "doctor.ps1 -Fix should generate route summary"
  Assert-True (Test-Path -LiteralPath (Join-Path $doctorIndexDir "DETAILED_CLASSIFICATION.md")) "doctor.ps1 -Fix should generate classification summary"
  Assert-True (-not [string]::IsNullOrWhiteSpace([string]$doctorResult.sample.first_candidate)) "doctor.ps1 should run a sample recommendation"

  Assert-True (Test-Path -LiteralPath $installScript) "install-skill.ps1 should exist"
  $installDest = Join-Path $outputRoot "installed\skills\skill-selection-assistant"
  $installResult = (& $installScript -Destination $installDest -SkillsRoot $skillRoot -Force | Out-String | ConvertFrom-Json)
  Assert-True ($installResult.status -eq "installed") "install-skill.ps1 should report installed"
  Assert-True (Test-Path -LiteralPath (Join-Path $installDest "SKILL.md")) "installer should copy SKILL.md"
  Assert-True (Test-Path -LiteralPath (Join-Path $installDest ".skill-index\route-summary.json")) "installer should run first scan"
  Assert-True (Test-Path -LiteralPath (Join-Path $installDest ".skill-index\DETAILED_CLASSIFICATION.md")) "installer should generate classification summary"

  Assert-True (Test-Path -LiteralPath $pythonInstallScript) "install-skill.py should exist"
  $pythonInstallDest = Join-Path $outputRoot "python-installed\skills\skill-selection-assistant"
  $pythonInstallResult = (& python $pythonInstallScript --destination $pythonInstallDest --skills-root $skillRoot --skip-scan --force | Out-String | ConvertFrom-Json)
  Assert-True ($pythonInstallResult.status -eq "installed") "install-skill.py should report installed"
  Assert-True (Test-Path -LiteralPath (Join-Path $pythonInstallDest "SKILL.md")) "Python installer should copy SKILL.md"

  $selfOnlyRoot = Join-Path $outputRoot "self-only\skills"
  $selfOnlyDest = Join-Path $selfOnlyRoot "skill-selection-assistant"
  $selfOnlyInstall = (& $installScript -Destination $selfOnlyDest -SkillsRoot $selfOnlyRoot -Force | Out-String | ConvertFrom-Json)
  Assert-True ($selfOnlyInstall.status -eq "installed") "installer should support a self-only skills root"
  $selfOnlySummary = Read-Json -Path (Join-Path $selfOnlyDest ".skill-index\route-summary.json")
  Assert-True ([int]$selfOnlySummary.raw_total -eq 0) "scanner should exclude the router skill itself from candidates"
  $selfOnlyRecommendation = (& (Join-Path $selfOnlyDest "scripts\recommend-skills.ps1") -Query "analyze data" -Limit 3 -IndexDir (Join-Path $selfOnlyDest ".skill-index") -SkillsRoot $selfOnlyRoot | Out-String | ConvertFrom-Json)
  Assert-True ([int]$selfOnlyRecommendation.selection.returned -eq 0) "self-only skills root should return no recommendations instead of recommending itself"

  Assert-True (Test-Path -LiteralPath $cleanScript) "clean-local-artifacts.ps1 should exist"
  $cleanPreview = (& $cleanScript -WhatIf | Out-String | ConvertFrom-Json)
  Assert-True ($cleanPreview.WhatIf -eq $true) "clean-local-artifacts.ps1 -WhatIf should be safe to preview"

  Assert-True (Test-Path -LiteralPath $packageScript) "package-release.ps1 should exist"
  $packageResult = (& $packageScript -Version "smoke-test" | Out-String | ConvertFrom-Json)
  Assert-True (Test-Path -LiteralPath $packageResult.Zip) "package-release.ps1 should create a zip"
  Assert-True ([int64]$packageResult.Length -gt 0) "package zip should not be empty"
  Add-Type -AssemblyName System.IO.Compression.FileSystem
  $archive = [System.IO.Compression.ZipFile]::OpenRead($packageResult.Zip)
  try {
    $artifactEntries = @($archive.Entries | Where-Object { $_.FullName -like "*skill-index*" -or $_.FullName -like "dist/*" })
    Assert-True ($artifactEntries.Count -eq 0) "package zip should exclude local artifacts"
    $zhReadmeEntries = @($archive.Entries | Where-Object { $_.FullName -eq "README.zh-CN.md" })
    Assert-True ($zhReadmeEntries.Count -eq 1) "package zip should include README.zh-CN.md"
    $installEntries = @($archive.Entries | Where-Object { $_.FullName -like "*scripts*install-skill.ps1" })
    Assert-True ($installEntries.Count -eq 1) "package zip should include install-skill.ps1"
    $pythonInstallEntries = @($archive.Entries | Where-Object { $_.FullName -like "*scripts*install-skill.py" })
    Assert-True ($pythonInstallEntries.Count -eq 1) "package zip should include install-skill.py"
    $doctorEntries = @($archive.Entries | Where-Object { $_.FullName -like "*skill-selection-assistant*scripts*doctor.ps1" })
    Assert-True ($doctorEntries.Count -eq 1) "package zip should include doctor.ps1"
    $summarizeEntries = @($archive.Entries | Where-Object { $_.FullName -like "*skill-selection-assistant*scripts*summarize-index.py" })
    Assert-True ($summarizeEntries.Count -eq 1) "package zip should include summarize-index.py"
  }
  finally {
    $archive.Dispose()
  }
  Remove-Item -LiteralPath $packageResult.Zip -Force

  [pscustomobject]@{
    Status = "passed"
    OutputDir = $indexDir
    RawTotal = $index.raw_total
    Total = $index.total
    DuplicatesRemoved = $index.duplicates_removed
    ManifestCacheFile = $manifest.cache_file
    RulesSchemaVersion = $summary.rules_schema_version
    FrontendCategory = $frontendRouteInference.category
    FirstRecommendation = $recommendation.selection.candidates[0].name
  } | ConvertTo-Json -Depth 4
}
finally {
  if ((-not $KeepOutput) -and (Test-Path -LiteralPath $outputRoot)) {
    Remove-Item -LiteralPath $outputRoot -Recurse -Force
  }
}
