param(
  [switch]$KeepOutput
)

$ErrorActionPreference = "Stop"

function Assert-True {
  param([bool]$Condition, [string]$Message)
  if (-not $Condition) {
    throw "ASSERTION FAILED: $Message"
  }
}

function Read-Json {
  param([string]$Path)
  return (Get-Content -LiteralPath $Path -Raw -Encoding UTF8 | ConvertFrom-Json)
}

$repoRoot = Resolve-Path -LiteralPath (Join-Path $PSScriptRoot "..")
$skillRoot = Join-Path $repoRoot "tests\fixtures\skills"
$scanScript = Join-Path $repoRoot "skill-selection-assistant\scripts\scan-local-skills.ps1"
$inferScript = Join-Path $repoRoot "skill-selection-assistant\scripts\infer-route.ps1"
$recommendScript = Join-Path $repoRoot "skill-selection-assistant\scripts\recommend-skills.ps1"
$cleanScript = Join-Path $repoRoot "scripts\clean-local-artifacts.ps1"
$packageScript = Join-Path $repoRoot "scripts\package-release.ps1"
$rulesPath = Join-Path $repoRoot "skill-selection-assistant\rules\categories.json"
$outputRoot = Join-Path $env:TEMP ("skill-selection-smoke-" + [guid]::NewGuid().ToString("N"))
$indexDir = Join-Path $outputRoot ".skill-index"

try {
  New-Item -ItemType Directory -Force -Path $indexDir | Out-Null

  & $scanScript -SkillsRoot $skillRoot -OutputDir $indexDir | Out-Null

  $indexPath = Join-Path $indexDir "skills-index.json"
  $summaryPath = Join-Path $indexDir "route-summary.json"
  $manifestPath = Join-Path $indexDir "manifest.json"
  $parseCachePath = Join-Path $indexDir "parsed-skills-cache.ndjson"
  Assert-True (Test-Path -LiteralPath $rulesPath) "shared category rules should exist"
  Assert-True (Test-Path -LiteralPath $indexPath) "skills-index.json should be generated"
  Assert-True (Test-Path -LiteralPath $summaryPath) "route-summary.json should be generated"
  Assert-True (Test-Path -LiteralPath $manifestPath) "manifest.json should be generated"
  Assert-True (Test-Path -LiteralPath $parseCachePath) "parsed-skills-cache.ndjson should be generated"

  $index = Read-Json -Path $indexPath
  $manifest = Read-Json -Path $manifestPath
  $summary = Read-Json -Path $summaryPath
  Assert-True ([int]$index.raw_total -eq 7) "raw_total should be 7"
  Assert-True ([int]$index.total -eq 6) "total should preserve same-name variants and merge exact duplicates"
  Assert-True ([int]$index.duplicates_removed -eq 1) "duplicates_removed should be 1"
  Assert-True ($summary.index_scope -eq "installing-user-local-skills") "route summary should declare per-user index scope"
  Assert-True ($summary.skill_instance_dir -ne $summary.skills_root) "summary should distinguish the installed skill instance from the scanned skills root"
  Assert-True ($manifest.cache_file -eq "parsed-skills-cache.ndjson") "manifest should point to NDJSON parse cache"
  Assert-True ($summary.rules_schema_version -eq "1.0") "route summary should expose shared rules schema"
  Assert-True ($null -eq $manifest.files[0].item) "manifest should not embed full parsed skill items"

  $duplicateVariants = @($index.skills | Where-Object { $_.canonical_name -eq "duplicate-tool" })
  Assert-True ($duplicateVariants.Count -eq 2) "duplicate-tool should have two content variants"
  Assert-True ((@($duplicateVariants | Where-Object { $_.dedupe_status -eq "variant" }).Count) -eq 2) "duplicate-tool variants should be marked variant"

  $frontendShortlist = Join-Path $indexDir "shortlists\domain-detail\frontend-web.json"
  $frontendRoute = Join-Path $indexDir "routes\domain-detail\frontend-web.json"
  Assert-True (Test-Path -LiteralPath $frontendShortlist) "frontend-web shortlist should exist"
  Assert-True (-not (Test-Path -LiteralPath $frontendRoute)) "frontend-web full route should not be generated by default"

  $staleFile = Join-Path $indexDir "routes\domain-detail\stale-route.json"
  New-Item -ItemType Directory -Force -Path (Split-Path -Parent $staleFile) | Out-Null
  Set-Content -LiteralPath $staleFile -Value "{}" -Encoding UTF8
  Assert-True (Test-Path -LiteralPath $staleFile) "stale route fixture should exist before rescan"
  & $scanScript -SkillsRoot $skillRoot -OutputDir $indexDir | Out-Null
  Assert-True (-not (Test-Path -LiteralPath $staleFile)) "stale route file should be removed by rescan"
  Assert-True (-not (Test-Path -LiteralPath $frontendRoute)) "default rescan should keep full routes absent"

  & $scanScript -SkillsRoot $skillRoot -OutputDir $indexDir -IncludeFullRoutes | Out-Null
  Assert-True (Test-Path -LiteralPath $frontendRoute) "frontend-web full route should exist when -IncludeFullRoutes is used"
  $fullRouteSummary = Read-Json -Path $summaryPath
  Assert-True ($fullRouteSummary.full_routes_generated -eq $true) "route summary should record full route generation"

  $frontendRouteInference = (& $inferScript -Query "build a beautiful frontend UI" -IndexDir $indexDir | Out-String | ConvertFrom-Json)
  Assert-True ($frontendRouteInference.category -eq "frontend-web") "frontend query should infer frontend-web"
  Assert-True ($frontendRouteInference.shortlist_file -eq "shortlists/domain-detail/frontend-web.json") "frontend inference should expose shortlist file"

  $researchRouteInference = (& $inferScript -Query "analyze this academic paper and extract citations" -IndexDir $indexDir | Out-String | ConvertFrom-Json)
  Assert-True ($researchRouteInference.category -eq "academic-research") "academic query should infer academic-research"

  $recommendation = (& $recommendScript -Query "build a beautiful frontend UI" -Limit 3 -IndexDir $indexDir | Out-String | ConvertFrom-Json)
  Assert-True ($recommendation.route.category -eq "frontend-web") "recommendation should use frontend-web route"
  Assert-True ($recommendation.selection.source_file -like "*shortlists*") "recommendation should read from shortlist"
  Assert-True ([int]$recommendation.selection.returned -gt 0) "recommendation should return candidates"
  Assert-True ($recommendation.selection.candidates[0].name -eq "frontend-design") "frontend-design should be first for frontend UI query"
  Assert-True ($recommendation.selection.merged_variants -eq $true) "recommendation should merge same-name variants by default"

  Assert-True (Test-Path -LiteralPath $cleanScript) "clean-local-artifacts.ps1 should exist"
  $cleanPreview = (& $cleanScript -WhatIf | Out-String | ConvertFrom-Json)
  Assert-True ($cleanPreview.WhatIf -eq $true) "clean-local-artifacts.ps1 -WhatIf should be safe to preview"

  Assert-True (Test-Path -LiteralPath $packageScript) "package-release.ps1 should exist"
  $packageResult = (& $packageScript -Version "smoke-test" | Out-String | ConvertFrom-Json)
  Assert-True (Test-Path -LiteralPath $packageResult.Zip) "package-release.ps1 should create a zip"
  Assert-True ([int64]$packageResult.Length -gt 0) "package zip should not be empty"
  Add-Type -AssemblyName System.IO.Compression.FileSystem
  $archive = [System.IO.Compression.ZipFile]::OpenRead($packageResult.Zip)
  try {
    $artifactEntries = @($archive.Entries | Where-Object { $_.FullName -like "*skill-index*" -or $_.FullName -like "dist/*" })
    Assert-True ($artifactEntries.Count -eq 0) "package zip should exclude local artifacts"
  }
  finally {
    $archive.Dispose()
  }
  Remove-Item -LiteralPath $packageResult.Zip -Force

  [pscustomobject]@{
    Status = "passed"
    OutputDir = $indexDir
    RawTotal = $index.raw_total
    Total = $index.total
    DuplicatesRemoved = $index.duplicates_removed
    ManifestCacheFile = $manifest.cache_file
    RulesSchemaVersion = $summary.rules_schema_version
    FrontendCategory = $frontendRouteInference.category
    FirstRecommendation = $recommendation.selection.candidates[0].name
  } | ConvertTo-Json -Depth 4
}
finally {
  if ((-not $KeepOutput) -and (Test-Path -LiteralPath $outputRoot)) {
    Remove-Item -LiteralPath $outputRoot -Recurse -Force
  }
}
